version: '3'

networks:
  db:
    driver: bridge

services:
  master:
    build:
      context: ./master
    environment:
      TZ: Asia/Shanghai
      MYSQL_ROOT_PASSWORD: root
    networks:
      - db
    ports:
      - '33060:3306'
    volumes:
      - ./master/data:/var/lib/mysql
      - ./master/conf:/etc/mysql/mysql.conf.d

  slave1:
      build:
        context: ./slave1
      environment:
        TZ: Asia/Shanghai
        MYSQL_ROOT_PASSWORD: root
      networks:
        - db
      ports:
        - '33061:3306'
      volumes:
        - ./slave1/data:/var/lib/mysql
        - ./slave1/conf:/etc/mysql/mysql.conf.d

  slave2:
    build:
      context: ./slave2
    environment:
      TZ: Asia/Shanghai
      MYSQL_ROOT_PASSWORD: root
    networks:
      - db
    ports:
      - '33062:3306'
    volumes:
      - ./slave2/data:/var/lib/mysql
      - ./slave2/conf:/etc/mysql/mysql.conf.d
